name: CI Pipeline

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ghcr.io/ravikumar-dekka/my-project/sample-web-app:1.0

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: HTML syntax check
      run: |
        sudo apt-get update
        sudo apt-get install -y tidy
        tidy -e index.html

    - name: Build Docker Image
      run: docker build -t sample-web-app:1.0 .

    - name: Scan Docker image with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: sample-web-app:1.0
        severity: HIGH,CRITICAL

    - name: Login to GitHub Container Registry
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Tag Docker image
      run: docker tag sample-web-app:1.0 $IMAGE_NAME

    - name: Push Docker image to GHCR
      run: docker push $IMAGE_NAME


  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Kind
      run: |
        curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.22.0/kind-linux-amd64
        chmod +x ./kind
        sudo mv ./kind /usr/local/bin/kind

    - name: Install kubectl
      uses: azure/setup-kubectl@v4

    - name: Create Kubernetes cluster
      run: kind create cluster

    - name: Deploy application to Kubernetes
      run: |
        kubectl create deployment sample-web-app \
          --image=ghcr.io/ravikumar-dekka/my-project/sample-web-app:1.0

    - name: Expose service
      run: |
        kubectl expose deployment sample-web-app \
          --type=NodePort \
          --port=80

    - name: Wait for deployment to be ready
      run: kubectl rollout status deployment sample-web-app

    - name: Verify Pods
      run: kubectl get pods


  monitor:
    needs: deploy
    runs-on: ubuntu-latest

    steps:
    - name: Install kubectl
      uses: azure/setup-kubectl@v4

    - name: Install Kind
      run: |
        curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.22.0/kind-linux-amd64
        chmod +x ./kind
        sudo mv ./kind /usr/local/bin/kind

    - name: Create Kubernetes cluster
      run: kind create cluster

    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

    - name: Add Helm repos
      run: |
        helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
        helm repo add grafana https://grafana.github.io/helm-charts
        helm repo update

    - name: Install Prometheus & Grafana
      run: helm install monitoring prometheus-community/kube-prometheus-stack

    - name: Install Loki
      run: helm install loki grafana/loki-stack

    - name: Verify monitoring pods
      run: kubectl get pods -A
