name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: HTML syntax check
      run: |
        sudo apt-get update
        sudo apt-get install -y tidy
        tidy -e index.html

    - name: Build Docker Image
      run: docker build -t sample-web-app:1.0 .

    - name: Scan Docker image with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: sample-web-app:1.0
        severity: HIGH,CRITICAL

    - name: Login to GitHub Container Registry
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Tag Docker image
      run: docker tag sample-web-app:1.0 ghcr.io/${{ github.repository }}/sample-web-app:1.0

    - name: Push Docker image to GHCR
      run: docker push ghcr.io/${{ github.repository }}/sample-web-app:1.0
